config/routes.rb
Rails.application.routes.draw do
  
  root to: 'home#top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  devise_for :users
  
  resources :users do
  resources :posts
end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
    has_one :like
    belongs_to :user
    accepts_nested_attributes_for :like
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts
  
  validates :email, presence: true
  validates :password, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/concerns/common_actions.rb
module CommonActions
 #以下extendは必須
  extend ActiveSupport::Concern    
      # 登録後にいいねの数をランダムで更新していく。
    
def update_iine
    @post=Post.find(params[:id])
    @like=@post.like
    update_times=rand(1..5) # 何回更新するかをランダムで取得する。（10回から100回くらい？）（5回だとする。）
    
    update_times.times do
    
    # 1回目
    
    # 現在のいいねの数を取得する。
    
    add_iine=rand(1..1000) # 何いいねを足すか、ランダムで決める。（1から100くらい？）
    
    # 現在のいいね＋取得したいいねでDBの値を更新する。
    @post=Post.find(params[:id])
    @like=@post.like
    @like.update( likes: add_iine+@like.likes )
    
    # 次回まで何秒あけるかランダムで決める。（5秒から30くらい？）
    # sleep(5)  
    end
    
end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  include CommonActions
  
  after_action :update_iine, only: [:show]
  
  def new
    @post=Post.new
    @post.build_like
    @user=User.find_by(params[:id])
  end
  
  def create
      @post=Post.new(post_params)
      @post.save
      redirect_to user_posts_path
  end
  
  def index
    @user=User.find_by(params[:id])
    @posts=Post.where(user_id: @user.id).includes(:like)
  end
  
  def show
    @user=User.find_by(params[:id])
    @post=Post.find_by(id: params[:id])
    @like=@post.like
      respond_to do |format| 
      format.html # html形式でアクセスがあった場合は特に何もなし
      format.json { @update_like_count=@like.likes }# json形式でアクセスがあった場合は、@update_like_countに代入する
    end
    

  end
  
  def destroy
    @post=Post.find(params[:id])
    @post.destroy
  end
  
  private
  def post_params
    params.require(:post).permit(:description,:user_id, like_attributes:[:id,:post_id,:likes])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/top.html.erb
<%= javascript_pack_tag 't' %>

<div class="bg-primary mb-5">
<%= link_to "ログイン", new_user_session_path %>
<p>Buzztterは</p>
<p class="test">あなたのつぶやきを全力でいいね！して、リアルタイムで承認欲求を満たします</p>

<p>あなたの気持ちを盛り上げよう</p>

</div>

<script>
    $(function(){
      $(".test").t()
    });
    
</script>
<script>
  $('.test').t({
    speed:75,          // タイピングのスピードを指定します。
    speed_vary:false,  // 「true」にすると人間が入力しているかのように文字ごとのスピードが変わります。
    delay:false,       // 開始時間を指定します。
    mistype:false,     // 文字の打ち間違いをする確率を指定します。
    caret:true,        // 「true」にするとカーソルを非表示する事ができます。
    blink:false,       // 「true」にするとカーソルを点滅させる事ができます。
    tag:'span',        // テキストを囲むタグを指定します。
    repeat:false       // 何回リピートするか指定します。「true」を指定すると、無限にリピートします。
  }); 
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Buzztter</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    	
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="index-header">

</div>

<% @posts.each do |post|%>
<div class="tweet-content">
<%= link_to post.description, user_post_path(@user.id,post.id) %>
    <ul>
        <li><%= post.like.likes %></li>
    </ul>
<% end%>
</div>

<div>
<%= link_to "+" ,new_user_post_path %>
</div>

app/views/posts/new.html.erb
<%= link_to "キャンセル" , user_posts_path(@user.id) %>
<%= form_with model: [@user,@post] do |f| %>

<%= f.text_area :description,placeholder: "いまどうしてる？" %>
<%= f.hidden_field :user_id, :value => @user.id %>

<%= f.fields_for :like, @post.like do |l| %>
    <!--初期のいいねの数を1～300からランダムで登録する。-->
    <%= l.hidden_field :likes, :value => rand(1..300) %>
<% end %>

<%= f.submit "ツイート" %>

<% end %>

app/views/posts/show.html.erb
<%= javascript_pack_tag 'post' %>

<%= @post.description %>
<%= @post.created_at %>
<p>いいね！</p>
<p class="iine-count"><%= @like.likes %></p>
<p>リツイート！</p>